version: "3.9"
services:
  db-test:
    container_name: db_product
    image: postgres
    environment:
      POSTGRES_DB: ms_product
      POSTGRES_USER: omerSolutions
      POSTGRES_PASSWORD: Telomere2010
    ports:
      - "2100:2100"
    expose:
      - 2100
    command: -p 2100

  java-test:
    container_name: java-challenge
    image: pee-java-app:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
        - db-test
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db_product:2100/ms_product
        - SPRING_DATASOURCE_USERNAME=omerSolutions
        - SPRING_DATASOURCE_PASSWORD=Telomere2010